[DO NOT MERGE] Feature/lint
chirimen-oh/node-web-gpio pull request #22
Opened 2021-02-14 04:53 UTC by gurezo

eslint を導入して、下記エラー警告を修正中
```
   65:32  warning  Unexpected any. Specify a different type                                @typescript-eslint/no-explicit-any
  124:3   warning  Missing return type on function                                         @typescript-eslint/explicit-module-boundary-types
  137:38  warning  Unexpected any. Specify a different type                                @typescript-eslint/no-explicit-any
  150:11  error    Promise returned in function argument where a void return was expected  @typescript-eslint/no-misused-promises
  162:3   warning  Missing return type on function                                         @typescript-eslint/explicit-module-boundary-types
  163:36  warning  Unexpected any. Specify a different type                                @typescript-eslint/no-explicit-any
  177:3   warning  Missing return type on function                                         @typescript-eslint/explicit-module-boundary-types
  202:3   warning  Missing return type on function                                         @typescript-eslint/explicit-module-boundary-types
  234:8   error    Async function 'requestGPIOAccess' has no 'await' expression            @typescript-eslint/require-await

```

2021-02-14 05:12 UTC, gurezo commented
残作業
```
  150:11  error  Promise returned in function argument where a void return was expected  @typescript-eslint/no-misused-promises
  234:8   error  Async function 'requestGPIOAccess' has no 'await' expression            @typescript-eslint/require-await
```

2021-02-27 07:28 UTC, kou029w requested changes

2021-02-27 07:28 UTC, kou029w commented on index.ts
> +          () => this.read.bind(this),
振る舞いが変わっていますね。許容できない気がします。

2021-02-27 07:28 UTC, kou029w commented on index.ts
> +  async unexportAll(): Promise<void> {
明示的に戻り値の型注釈を書くことでより安全になって個人的には良いと感じました。

2021-02-27 07:28 UTC, kou029w commented on index.ts
> +  return new Promise((res) => {
ここでの変更の意図は何でしょうか? eslintのふるまいや静的コード解析と関係していますか?

2021-02-27 07:40 UTC, kou029w commented on package.json
> +    "lint": "npx eslint index.ts",
npxは省略可能ですね。

2021-02-27 07:40 UTC, kou029w commented on package-lock.json
> +{
yarn.lockと役割が近く、どちらか一方のみであるほうが望ましいと考えます。

2021-02-27 08:03 UTC, gurezo commented on package.json
> +    "lint": "npx eslint index.ts",
@kou029w 省略します

2021-02-27 08:04 UTC, gurezo commented on index.ts
> +          () => this.read.bind(this),
@kou029w  修正します。

2021-02-27 08:07 UTC, gurezo commented on index.ts
> +  return new Promise((res) => {
requestGPIOAccess の戻り値の型が、 Promise<GPIOAccess> になったので、
明確に Promise  で、返却しようする意図です。

2021-02-27 08:07 UTC, gurezo commented on package-lock.json
> +{
@kou029w  そうですね、削除します。

2021-02-27 08:14 UTC, kou029w commented on index.ts
> +  return new Promise((res) => {
async関数であることをやめたほうが望ましいということでしょうか。
またここ以外のasync関数に関してはいかがお考えでしょうか。
async関数であることはPromiseを返すことが明らかなのでは？と個人的には感じます。

2021-02-27 08:29 UTC, gurezo commented on index.ts
> +  return new Promise((res) => {
@kou029w 
> async関数であることをやめたほうが望ましいということでしょうか。
いえ、そういう意図はなく、eslint で warning や error を出さないために実装を変更した次第です。
明示的に実装した方が、初見の人にもメリットがあるのでは？と考えました。

> またここ以外のasync関数に関してはいかがお考えでしょうか。
他の箇所も同様で、、eslint で 対象となった箇所を明示的に変更しました。

他の箇所については、warning なので、修正無しでも良いとは思います。
L150, L234 については、明確に error となったので、今回の修正を施しました。

eslint パスし、冗長的な実装にならないようにもう一度見直してみます。
```
  150:11  error    Promise returned in function argument where a void return was expected  @typescript-eslint/no-misused-promises
  234:8   error    Async function 'requestGPIOAccess' has no 'await' expression            @typescript-eslint/require-await
```

レビューありがとうございます。

2021-02-27 08:41 UTC, kou029w commented on index.ts
> +  return new Promise((res) => {
ここで解決したかったルール違反は `@typescript-eslint/require-await` ですね、なるほど。
ここではWeb GPIOの仕様に基づく意図的なasync関数の使用なので、そもそもこのルールを無効化してもよいと私は考えます。

2021-02-27 09:06 UTC, gurezo commented on index.ts
> +  return new Promise((res) => {
@kou029w 
有難うございます。
L234は、無効キーワードを実装して対処します。

2021-03-02 04:51 UTC, kou029w commented on index.ts
> +  return new GPIOAccess(ports);
余計な空白:
```suggestion
  return new GPIOAccess(ports);
```

2021-03-21 07:05 UTC, gurezo commented on index.ts
> +  return new GPIOAccess(ports);
f728e1f　修正

2021-03-27 14:14 UTC, kou029w commented on .eslintrc.js
> +    ecmaVersion: 2019, // Node.js 12の場合は2019、他のバージョンのNode.jsを利用している場合は場合は適宜変更する
コメントを含め[こちらのnotakaosさんのQiita記事](
https://qiita.com/notakaos/items/85fd2f5c549f247585b1)のコードのコピペに見えるのですが原著者の許諾を受けており使用に問題無いということで正しいですか。

2021-03-28 05:48 UTC, gurezo commented on .eslintrc.js
> +    ecmaVersion: 2019, // Node.js 12の場合は2019、他のバージョンのNode.jsを利用している場合は場合は適宜変更する
@kou029w 
許諾を頂いていなかったので、確認いたします。

2021-03-28 08:14 UTC, gurezo commented on .eslintrc.js
> +    ecmaVersion: 2019, // Node.js 12の場合は2019、他のバージョンのNode.jsを利用している場合は場合は適宜変更する
@kou029w 
許可頂きました。
https://qiita.com/notakaos/items/85fd2f5c549f247585b1#comment-46b2599d1560f88acf82

2021-03-28 08:28 UTC, kou029w approved these changes
いろいろと細かい指摘事項にもご対応いただきありがとうございます！
レビューに時間をかけてしまって申し訳ないです。
LGTMです 👍

2021-03-28 08:31 UTC, merged